### ISSUE TITLE
TriggeredSend issues - FuelSDK::DescribeError: Unable to get TriggeredSend

### ISSUE THREAD

**Issue by alssndro** [barberj/fuelsdk#2]
Hi, first off thanks for maintaining a fork of the seemingly abandoned 'official' gem.

I am having the same issue that was present in the unmaintained version [here](https://github.com/ExactTarget/FuelSDK-Ruby/issues/19).

Using this gem, I can get a list of TriggeredSends and retrieve their status no problem.

Sending with a TriggeredSend does not work though, and always raises the error:

``` bash
FuelSDK::DescribeError: Unable to get TriggeredSend
from /Users/s/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:163:in `get_all_object_properties'
```

And the full error message with debug mode on:

``` xml
D, [2014-02-22T00:40:21.336074 #10338] DEBUG -- : HTTPI GET request to webservice.exacttarget.com (net_http)
I, [2014-02-22T00:40:22.100041 #10338]  INFO -- : SOAP request: https://webservice.s6.exacttarget.com/Service.asmx
I, [2014-02-22T00:40:22.100111 #10338]  INFO -- : SOAPAction: "Describe", Content-Type: text/xml;charset=UTF-8, Content-Length: 1238
D, [2014-02-22T00:40:22.100151 #10338] DEBUG -- : 

<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://exacttarget.com/wsdl/partnerAPI" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
<env:Header>
    <oAuth xmlns="http://exacttarget.com">
    <oAuthToken>[redacted]</oAuthToken>
</oAuth>
<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="UsernameToken-1">
<wsse:Username>*</wsse:Username>
<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">*</wsse:Password>
</wsse:UsernameToken>
</wsse:Security>
</env:Header>
<env:Body>
    <tns:DefinitionRequestMsg>
        <tns:DescribeRequests>
            <tns:ObjectDefinitionRequest>
                <tns:ObjectType>TriggeredSend</tns:ObjectType>
            </tns:ObjectDefinitionRequest>
        </tns:DescribeRequests>
    </tns:DefinitionRequestMsg>
</env:Body>
</env:Envelope>

D, [2014-02-22T00:40:22.100272 #10338] DEBUG -- : HTTPI POST request to webservice.s6.exacttarget.com (net_http)
I, [2014-02-22T00:40:23.519374 #10338]  INFO -- : SOAP response (status 200)
D, [2014-02-22T00:40:23.519457 #10338] DEBUG -- :
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
<soap:Header>
    <wsa:Action>DescribeResponse</wsa:Action>
    <wsa:MessageID>urn:uuid:1f47b68d-e788-4b63-9ec0-e0068be419db</wsa:MessageID>
    <wsa:RelatesTo>urn:uuid:5b481866-080f-469b-974a-6bd4414d7e5d</wsa:RelatesTo>
    <wsa:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To>
    <wsse:Security>
        <wsu:Timestamp wsu:Id="Timestamp-4404a62b-6aef-4c75-a8db-8c26d11cc70d">
            <wsu:Created>2014-02-22T00:40:23Z</wsu:Created>
            <wsu:Expires>2014-02-22T00:45:23Z</wsu:Expires>
        </wsu:Timestamp>
    </wsse:Security>
</soap:Header>
<soap:Body>
    <DefinitionResponseMsg xmlns="http://exacttarget.com/wsdl/partnerAPI">
    <RequestID>f8d496f5-98b0-48ec-a059-146338e5d01f</RequestID>
</DefinitionResponseMsg>
</soap:Body>
</soap:Envelope>
FuelSDK::DescribeError: Unable to get TriggeredSend
from /Users/s/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:163:in `get_all_object_properties'
```

I will continue to dig around the source, but any help would be appreciated.

Thanks

**Comment by udit7590** [comment]
I am too getting this issue. Any fix there yet?

**Comment by hcarreras** [comment]
Getting the same error...
